#!/usr/bin/env python3
"""
Build a single static dashboard that stitches together every forex report
generated by the other tools in this folder. No server, no network — open the
resulting forex/dashboard.html in a browser.

It scans forex_data/ for:
  * audusd_daily_lastweek.csv         -> week summary cards + chart
  * *_headlines.csv (most recent)     -> net news lean card
  * *_calendar.csv  (most recent)     -> upcoming high-impact events card
  * *_report.html                     -> embedded preview + link per report

Anything missing just shows a "run <tool>" placeholder, so the dashboard works
even before you've run everything.

Usage:  python3 forex/build_dashboard.py
Refresh the data first with:
  python3 forex/build_lastweek_report.py         # daily backtest review
  python3 forex/forex_backtest.py                # per-second backtest (needs net)
  python3 forex/news_sentiment.py                # forward news + sentiment (needs net)
"""
import os
import glob
import html
import datetime as dt

import pandas as pd

HERE = os.path.dirname(os.path.abspath(__file__))
DATA = os.path.join(HERE, "forex_data")
OUT = os.path.join(HERE, "dashboard.html")


def _latest(pattern):
    files = sorted(glob.glob(os.path.join(DATA, pattern)), key=os.path.getmtime, reverse=True)
    return files[0] if files else None


def rel(path):
    """Path relative to forex/ so links work when opening dashboard.html."""
    return os.path.relpath(path, HERE).replace(os.sep, "/")


def week_summary():
    # prefer this week's data if present, else last week's
    p = next((os.path.join(HERE, f) for f in
              ("audusd_daily_thisweek.csv", "audusd_daily_lastweek.csv")
              if os.path.exists(os.path.join(HERE, f))), None)
    if not p:
        return None
    d = pd.read_csv(p, parse_dates=["date"])
    in_progress = d["date"].iloc[-1].date() >= dt.date.today()
    first, last = d["close"].iloc[0], d["close"].iloc[-1]
    move = (last - first) / 0.0001
    pct = (last / first - 1) * 100
    return {
        "range": f"{d['date'].iloc[0]:%d %b} – {d['date'].iloc[-1]:%d %b %Y}",
        "close": last, "move": move, "pct": pct, "in_progress": in_progress,
        "dir": "UPTREND" if move > 0 else "DOWNTREND" if move < 0 else "FLAT",
    }


def news_lean():
    p = _latest("*_headlines.csv")
    if not p:
        return None
    d = pd.read_csv(p)
    if "pair_score" not in d.columns or d.empty:
        return None
    s = d["pair_score"].sum()
    return {
        "label": "UPTREND" if s > 0.3 else "DOWNTREND" if s < -0.3 else "NEUTRAL",
        "sum": s, "n": len(d), "file": p,
    }


def upcoming_events():
    p = _latest("*_calendar.csv")
    if p:
        d = pd.read_csv(p)
        high = d[d.get("impact", "") == "High"] if "impact" in d.columns else d
        return {"n_high": len(high), "n_total": len(d), "file": p, "df": d}
    # fall back to a bundled calendar (prefer this week's)
    p = next((os.path.join(HERE, f) for f in
              ("news_events_thisweek.csv", "news_events.csv")
              if os.path.exists(os.path.join(HERE, f))), None)
    if p:
        d = pd.read_csv(p)
        high = d[d["impact"] == "High"] if "impact" in d.columns else d
        return {"n_high": len(high), "n_total": len(d), "file": p, "df": d}
    return None


def card(title, big, sub, color="#2c3e50"):
    return (f"<div class='card'><div class='card-t'>{title}</div>"
            f"<div class='card-b' style='color:{color}'>{big}</div>"
            f"<div class='card-s'>{sub}</div></div>")


DIR_COLOR = {"UPTREND": "#1e8449", "DOWNTREND": "#c0392b", "NEUTRAL": "#7f8c8d",
             "FLAT": "#7f8c8d", None: "#7f8c8d"}


def main():
    ws = week_summary()
    nl = news_lean()
    ue = upcoming_events()
    reports = sorted(glob.glob(os.path.join(DATA, "*_report.html")), key=os.path.getmtime, reverse=True)

    cards = []
    if ws:
        wtitle = "This week so far (AUD/USD)" if ws.get("in_progress") else "Last week (AUD/USD)"
        cards.append(card(wtitle, f"{ws['move']:+.0f} pips",
                          f"{ws['range']} · {ws['pct']:+.2f}% · {ws['dir']}", DIR_COLOR[ws["dir"]]))
        cards.append(card("Latest close", f"{ws['close']:.5f}",
                          "in progress" if ws.get("in_progress") else "daily backtest review"))
    else:
        cards.append(card("Last week", "—", "run build_lastweek_report.py"))
    if nl:
        cards.append(card("News lean (forward)", nl["label"],
                          f"{nl['n']} headlines · score {nl['sum']:+.2f}", DIR_COLOR[nl["label"]]))
    else:
        cards.append(card("News lean (forward)", "—", "run news_sentiment.py"))
    if ue:
        cards.append(card("Upcoming events", f"{ue['n_high']} high-impact",
                          f"{ue['n_total']} tracked"))
    else:
        cards.append(card("Upcoming events", "—", "no calendar data"))

    with open(OUT, "w") as f:
        f.write("<!DOCTYPE html><html><head><meta charset='utf-8'>")
        f.write("<title>Forex dashboard — AUD/USD</title>")
        f.write("<style>"
                "body{font-family:-apple-system,Segoe UI,sans-serif;margin:0;background:#f4f6f8;color:#222}"
                "header{background:#1f2d3d;color:#fff;padding:1.1rem 1.5rem}"
                "header h1{margin:0;font-size:1.3rem}header p{margin:.3rem 0 0;opacity:.7;font-size:.85rem}"
                "main{max-width:1080px;margin:0 auto;padding:1.2rem}"
                ".cards{display:flex;flex-wrap:wrap;gap:1rem;margin-bottom:1.2rem}"
                ".card{background:#fff;border-radius:10px;padding:1rem 1.2rem;flex:1 1 200px;"
                "box-shadow:0 1px 3px rgba(0,0,0,.08)}"
                ".card-t{font-size:.75rem;text-transform:uppercase;letter-spacing:.5px;color:#8a97a5}"
                ".card-b{font-size:1.7rem;font-weight:700;margin:.25rem 0}.card-s{font-size:.8rem;color:#6b7785}"
                "section{background:#fff;border-radius:10px;padding:1rem 1.2rem;margin-bottom:1.2rem;"
                "box-shadow:0 1px 3px rgba(0,0,0,.08)}h2{font-size:1.05rem;margin:.2rem 0 .8rem}"
                "iframe{width:100%;height:520px;border:1px solid #e2e6ea;border-radius:6px}"
                "table{border-collapse:collapse;width:100%;font-size:.82rem}"
                "th,td{border:1px solid #e2e6ea;padding:4px 8px;text-align:left}th{background:#f0f3f6}"
                ".up{color:#1e8449;font-weight:600}.dn{color:#c0392b;font-weight:600}"
                "a{color:#2565c7}.muted{color:#8a97a5;font-size:.8rem}"
                "code{background:#eef1f4;padding:1px 5px;border-radius:4px}"
                "</style></head><body>")
        f.write("<header><h1>Forex dashboard — AUD/USD</h1>"
                f"<p>Static build · generated {dt.datetime.now():%Y-%m-%d %H:%M} · "
                "refresh by re-running the tools then this script</p></header><main>")

        f.write("<div class='cards'>" + "".join(cards) + "</div>")

        # upcoming events table
        if ue is not None:
            d = ue["df"]
            f.write("<section><h2>Upcoming / tracked events</h2><table><tr>")
            cols = [c for c in ["time", "currency", "event", "impact", "forecast",
                                "previous", "if_beats", "if_misses"] if c in d.columns]
            f.write("".join(f"<th>{c}</th>" for c in cols) + "</tr>")
            def cell(v):
                return "" if pd.isna(v) else html.escape(str(v))
            for _, r in d.iterrows():
                f.write("<tr>" + "".join(f"<td>{cell(r[c])}</td>" for c in cols) + "</tr>")
            f.write(f"</table><p class='muted'>source: {rel(ue['file'])}</p></section>")

        # embedded reports
        if reports:
            for rp in reports:
                name = os.path.basename(rp).replace("_report.html", "").replace("_", " ")
                f.write(f"<section><h2>{html.escape(name)}</h2>"
                        f"<p><a href='{rel(rp)}' target='_blank'>open full report ↗</a></p>"
                        f"<iframe src='{rel(rp)}' loading='lazy'></iframe></section>")
        else:
            f.write("<section><p class='muted'>No reports yet — run the report tools first.</p></section>")

        f.write("<section><h2>Refresh</h2><p class='muted'>"
                "<code>python3 forex/build_lastweek_report.py</code> · "
                "<code>python3 forex/forex_backtest.py</code> (needs network) · "
                "<code>python3 forex/news_sentiment.py</code> (needs network) · then "
                "<code>python3 forex/build_dashboard.py</code></p></section>")
        f.write("</main></body></html>")

    print("wrote", OUT)
    print(f"  cards: week={'y' if ws else 'n'} lean={'y' if nl else 'n'} events={'y' if ue else 'n'}")
    print(f"  embedded reports: {len(reports)}")


if __name__ == "__main__":
    main()
